paste/urls.py
from django.urls import path

from .views import CommentThread, Detail, Index, RawContent, AllPastes

app_name = "paste"

urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("p/<str:slug>/", Detail.as_view(), name="detail"),
    path("comment/<int:id>/", CommentThread.as_view(), name="thread"),
    path("raw/<str:slug>/", RawContent.as_view(), name="raw_content"),
    path("allpastes/", AllPastes.as_view(), name="all_pastes"),
]

pasteRand/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

from paste import views

urlpatterns = [
    path("admin/", admin.site.urls), path("", include("paste.urls")),
    ]

paste/models.py
import uuid

from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.utils.timezone import now


class PasteFile(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    slug = models.SlugField(unique=True)
    date_time = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("paste:detail", kwargs={"slug": self.slug})

    def get_slug(self):
        uuid_value = str(uuid.uuid4())
        unique_slug = slugify(uuid_value[0:13])
        return unique_slug

    def save(self, *args, **kwargs):
        self.slug = self.get_slug()
        return super(PasteFile, self).save(*args, **kwargs)


class Comment(models.Model):
    paste_file = models.ForeignKey(
        "paste.PasteFile", on_delete=models.CASCADE, related_name="comments", null=True
    )
    comment_text = models.TextField()
    parent = models.ForeignKey("self", on_delete=models.CASCADE, null=True, blank=True)
    slug = models.SlugField()

    def __str__(self):
        return self.comment_text

    # replies
    def children(self):
        return self.__class__.objects.filter(parent=self)

paste/forms.py
from django import forms
from django.forms import ModelForm

from .models import Comment, PasteFile


class PasteForm(ModelForm):
    content = forms.CharField(
        required=False, widget=forms.Textarea(attrs={"rows": 15, "cols": 120})
    )

    class Meta:
        model = PasteFile
        fields = ("title", "content")


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("comment_text",)

paste/views.py
from django.shortcuts import get_object_or_404, redirect, render, HttpResponse
from django.urls import reverse
from django.views.generic import CreateView, DetailView
from django.http import HttpResponse

from .forms import CommentForm, PasteForm
from .models import Comment, PasteFile

from rest_framework.response import Response
from rest_framework import status
import json


class Index(CreateView):
    model = PasteFile
    form_class = PasteForm


class Detail(DetailView):
    template_name = "paste/detail.html"
    model = PasteFile

    def get(self, request, slug):
        paste_obj = get_object_or_404(PasteFile, slug=slug)
        context = dict(
            object=paste_obj,
            comments=Comment.objects.filter(paste_file__id=paste_obj.id),
            form=CommentForm(),
            slug=slug,
        )
        return render(request, self.template_name, context)

    def post(self, request, slug):
        if request.method == "POST":
            form = CommentForm(request.POST)
            if form.is_valid():
                post = get_object_or_404(PasteFile, slug=slug)
                comment = form.save(commit=False)
                comment.paste_file = post
                comment.slug = post.slug
                comment.save()
                return redirect(post.get_absolute_url())
        return render(request, self.template_name, paste_content)


class CommentThread(CreateView):
    template_name = "paste/comment_thread.html"
    form_class = CommentForm
    http_method_names = ["get", "post"]

    def form_valid(self, form):
        self.parent_comment = self.get_parent_comment()
        form = form.save(commit=False)
        form.paste_file = self.parent_comment.paste_file
        form.parent = self.parent_comment
        form.slug = self.parent_comment.slug
        return super().form_valid(form)

    def get_parent_comment(self):
        return get_object_or_404(Comment, id=self.kwargs.get("id"))

    def get_success_url(self):
        return reverse("paste:detail", kwargs={"slug": self.parent_comment.slug})


class RawContent(DetailView):
    model = PasteFile

    def get(self, request, slug):
        paste_obj = get_object_or_404(PasteFile, slug=slug)
        context = paste_obj.content
        return HttpResponse(context, content_type="text/plain; charset=utf8")


class AllPastes(DetailView):
    def get(self, request):
        pastes = PasteFile.objects.all()
        pastes_list = []
        for paste in pastes:
            paste_dict = {}
            paste_dict['title'] = paste.title
            paste_dict['content'] = paste.content
            paste_dict['url'] = request.build_absolute_uri(paste.get_absolute_url())
            paste_dict['date_time'] = paste.date_time.strftime('%Y-%m-%dT%H:%M:%S.%f')
            pastes_list.append(paste_dict)
        return HttpResponse(json.dumps(pastes_list), content_type="application/json")

paste/templates/base.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
{% load static %}
<link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>
<link href="{% static 'css/custom.css' %}" rel="stylesheet" />
<link href="{% static 'css/nes.min.css' %}" rel="stylesheet" />
<link href="{% static 'css/print.css' %}" rel="stylesheet" media="print" />
<link href="{% static 'css/highlight.default.min.css' %}" rel="stylesheet"/>
<link href="{% static 'css/custom.css' %}" rel="stylesheet"/>
<script type="text/javascript" src="{% static 'js/highlight.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/highlightjs-line-numbers.min.js' %}"></script>
<script>hljs.initHighlightingOnLoad();hljs.initLineNumbersOnLoad();</script>
<title>{{ title }}</title>
</head>
<body>
  <a class="github-link" :class="{ active:  scrollPos < 200 }" href="https://github.com/furkanonder/pasteRand" target="_blank" rel="noopener" @mouseover="startAnimate" @mouseout="stopAnimate">
    <p class="nes-balloon from-right">Fork me<br />on GitHub</p>
    <i class="nes-octocat" :class="animateOctocat ? 'animate' : ''"></i>
  </a>
  <br>
  <center>
    <a href="{% url 'paste:index' %}">
      <img class="logo" src="{% static 'img/logo.png' %}">
    </a>
  </center>
  {% block content %}
  {% endblock content %}
</body>
</html>

paste/templates/paste/comment_thread.html
{% extends 'base.html' %}

{% block content %}
<div id="comment_create" class="nes-container">
  <form method="POST">
  {% csrf_token %}
  {% for field in form %}
  <div>
    {{ field.errors }}
    {{ field.label_tag }}<br>
    {{ field }}
  </div>
  {% endfor %}
  <br>
  <button type="submit" class="nes-btn is-primary">Paste!</button>
</div>
{% endblock %}

paste/templates/paste/detail.html
{% extends 'base.html' %}

{% block content %}
<div id="detail_page" class="nes-container with-title ">
  <a style="float: right;" class="nes-btn is-primary" href="{% url 'paste:raw_content' slug=slug %}">Raw!</a>
  <p class="title">{{ object.title }}</p>
  <b>Creation date & time:</b>{{ object.date_time }}
  <pre class="code">
    <code>{{ object.content }}</code>
  </pre>
</div>

<div class="comments">
  <h2>Comments</h2>
  {% for comment in comments %}
    {% if comment.parent == None %}
    <div class="nes-container is-rounded">
      <p>{{ comment.comment_text }}</p>
      <div class="lists">
        {% if comment.children.count > 0 %}
          <b>
            <p>Replies: {{ comment.children.count }}</p>
          </b>
        {% endif %}
      </div>
      <div class="lists">
        {% for child_comment in comment.children %}
        <ul class="nes-list is-disc">
          <li>{{ child_comment.comment_text }}</li>
        </ul>
          {% endfor %}
        <a class="nes-btn is-warning" href="{% url 'paste:thread' id=comment.id %}">reply</a>
      </div>
    </div>
    {% endif %}
  {% empty %}
    <p>No comments here yet.</p>
  {% endfor %}
</div>

<div id="comment_create" class="nes-container">
  <form method="POST">
    {% csrf_token %}
    {% for field in form %}
    <div>
      {{ field.errors }}
      {{ field.label_tag }}<br>
      {{ field }}
    </div>
    {% endfor %}
  <button type="submit" class="nes-btn is-success">Send!</button>
  </form>
</div>
{% endblock %}

paste/templates/paste/index.html
{% extends 'base.html' %}

{% block content %}
<center>
  <div style="width: 1200px" class="nes-container with-title is-centered">
    <form method="POST">
    {% csrf_token %}
      <div class="nes-field">
        {{ form }}
      </div>
    <br>  
    <button type="submit" class="nes-btn is-primary">Paste!</button>   
{% endblock %} 
  </div>
</center>

paste/templates/paste/pastefile_form.html
{% extends 'base.html' %}

{% block content %}
  <div id="index_page" class="nes-container">
    <form method="POST">
    {% csrf_token %}
    {% for field in form %}
    <div class="container">
      {{ field.errors }}
      {{ field.label_tag }}<br>
      {{ field }}
    </div>
    {% endfor %}
    <br>
    <button type="submit" class="nes-btn is-primary">Paste!</button>
  </div>
{% endblock %}